### ISSUE TITLE
Cleaning up the personality file

### ISSUE THREAD

**Issue by KaySackey** [ironman5366/W.I.L.L#1]
I'd be happy to help, if you'd tell me what the format of personality.txt is and what the personality file is supposed to be doing.

I understand it has something to do with the greetings, I just can't figure out if its dependant on what you say to the bot or some other internal state of things.

**Comment by ironman5366** [comment]
Sure that would be awesome thanks. It's pretty basic. Each line in personality.txt represents an output. The actual output comes first, followed bt a colon, then the time of day (Morning, Afternoon, Night, Neutral). Then comes a comma and the politeness rating of the greeting from 0-10. Then a semicolon and the humor rating through 0-10. Then comes a / and then f=the trigger word. You can see this at https://github.com/ironman5366/W.I.L.L/blob/master/personality.txt by the way. The trigger word is the kind of greeting that it's bound to. Right now I have hello and goodbye. Then the idea is that the program will pick a greeting based on the kind of word that W.I.L.L tells it to look for, the time of day, and the personality settings located in output.txt https://github.com/ironman5366/W.I.L.L/blob/master/output.txt. However, while it works fine, I'm not all that attached to the way it works and I've been planning to improve it for awhile. If you have any ideas or concepts you're toying with, feel free to implement them. A cleaner module would also additionally work as a plugin, but I can implement that at a later date. Thanks!

**Comment by ironman5366** [comment]
As somebody stepped in and cleaned it up, I'm closing the issue for now. It's alot better, although I still plan to improve the whole personality concept at some point.
