### ISSUE TITLE
requirements file missing

### ISSUE THREAD

**Issue by vms20591** [ironman5366/W.I.L.L#11]
@ironman5366 First I would like to say its a very good work :+1: 

The requirements file seems to be missing and if you happen to have one push it to the repo would be helpful. I am going the hard way of installing all the missing modules :D :D

**Comment by ironman5366** [comment]
I'll try to find the time to make one this weekend, I've just been swamped lately.

**Comment by ironman5366** [comment]
Pushed one

**Comment by vms20591** [comment]
Thats cool :)
