### ISSUE TITLE
Program doesn't exit on Ctrl+C

### ISSUE THREAD

**Issue by vms20591** [ironman5366/W.I.L.L#12]
@ironman5366 The main script doesn't exit even after issuing Ctrl+C and noticed that the thread used to execute Slack rtm reader wasn't marked as daemon.

W.I.L.L/main.py

```

logs.write("Debug value is {0}".format(debugval), 'working')
logs.write("Connecting to rtm socket", 'trying')
t = threading.Thread(target=slack)
t.start()
logs.write("Starting flask server on localhost", 'trying')
print app.run(debug=debugval, use_reloader=False)
```

Setting the thread as daemon would fix the issue.

**Comment by ironman5366** [comment]
I merged the daemon pull request and it should be fixed now

**Comment by vms20591** [comment]
Thanks :)
