### ISSUE TITLE
Logger throws exception if config information isn't found

### ISSUE THREAD

**Issue by brenttaylor** [ironman5366/W.I.L.L#23]
A proper error should be sent to stderr and the application should exit if information on the logger couldn't be found.

**Comment by Rich700000000000** [comment]
Yeah, I got that myself a few times.. Could we define an error?

**Comment by brenttaylor** [comment]
I'll hammer it out in a bit.

**Comment by Rich700000000000** [comment]
So, this error is closed, right?

**Comment by brenttaylor** [comment]
Correct.  It throws an error to the console buffer explaining the problem and exits.
