### ISSUE TITLE
Entering "cnn" breaks everything & makes the script hang/freeze. 

### ISSUE THREAD

**Issue by Rich700000000000** [ironman5366/W.I.L.L#24]
I entered "cnn", all lowercase, into slack. The script responded by printing 2,000 characters of random HTML and hanging, but not before sending an error TO SLACK, and filling _it_ up with errors and HTML.

Just, why...

**Comment by brenttaylor** [comment]
Looks like input is being parsed but not validated.  That's a problem and needs to be fixed.  However if you type "cnn <some text to search>" it works for now. @ironman5366 You up for fixing this?

**Comment by ironman5366** [comment]
I'll check it out.

**Comment by ironman5366** [comment]
Ok so I figured out what happened. When W.I.L.L doesn't detect a plugin or anything he can use, he runs it through the search module. That led him to check the cnn page. As referenced at https://github.com/ironman5366/W.I.L.L/issues/18, right now the html parsing is just an example and fairly awful. It just searches for a paragraph tag, but he didn't find one on that page so the error was that the search function didn't return anything. A quick fix would just to be have the search function return something that said nothing found upon that occasion, I'll do so now.

**Comment by ironman5366** [comment]
Fixed with https://github.com/ironman5366/W.I.L.L/commit/a9ab5881c98a1a7dd60a36703556362c7387fd56
