### ISSUE TITLE
WILL multiplies instead of adding.

### ISSUE THREAD

**Issue by Rich700000000000** [ironman5366/W.I.L.L#26]
I entered "What is 3 + 3", and it gave me 9. I entered "What is 22 + 22", and it gave me 484. This should be simple to clear up, right?

**Comment by ironman5366** [comment]
It actually might not be. W.I.L.L has no dedicated math module, he instead uses wolframalpha since you're asking questions. The only fix would be to create a separate math plugin or add something of the sort to the search plugin. If you'd like me to I'll add it to my list

**Comment by brenttaylor** [comment]
Well wolfram alpha seems to be working just fine, my guess is that the '+' symbol isn't being encoded properly.  Just a guess off the top of my head without the code in front of me.

**Comment by ironman5366** [comment]
Just confirmed that this is due to slack encoding the command improperly. In the easygui based debugging client it worked.
