### ISSUE TITLE
WILL calling plugin results in traceback

### ISSUE THREAD

**Issue by asharahmed** [ironman5366/W.I.L.L#29]
[log.txt](https://github.com/ironman5366/W.I.L.L/files/294305/log.txt)

after creating a plugin using WILL's plugin creation utility, I get a traceback error while trying to call my function which is contained in my file, testPlugin.py.

Logs are contained within this issue along with the testplugin 
[testPlugin.txt](https://github.com/ironman5366/W.I.L.L/files/294307/testPlugin.txt)

**Comment by ironman5366** [comment]
Hi Ashar, can you please attach your plugin.json file?

**Comment by asharahmed** [comment]
[plugin.txt](https://github.com/ironman5366/W.I.L.L/files/294368/plugin.txt)
