### ISSUE TITLE
Increasing greetings

### ISSUE THREAD

**Issue by sathe-aditya** [ironman5366/W.I.L.L#33]
Hello!
I'm new here, and was exploring around, when I observed that 'personality.txt' and 'personality.py' have greetings specific to a certain time of the day.
I feel that maybe an addition of the day could be made, which can incorporate sentences such as, 'How is your Sunday going?', or 'TGIF! What are your plans for tonight?'
This can increase the number of sentences W.I.L.L. can greet with!

Again, I am new here and have just observed this, please guide me in the correct direction if I am going wrong! :)

**Comment by ironman5366** [comment]
Hi! Thanks for taking interest in W.I.L.L! Those are great suggestions for further greetings, and I'd be happy to implement them. However, I'll have to do it down the road. Right now, I'm working on an overhaul of the framework. But once it's finished, I'd be happy to put these into the new config. I'll keep this issue open so I can remember to do that when I merge the new framework through. Thanks!

**Comment by sathe-aditya** [comment]
Hey! It's great that my suggestions are of some value. :) 
If you don't mind, may I work on it and issue a pull request?

**Comment by ironman5366** [comment]
Sure! However, when the dev branch gets pulled through in a month or so, it's gonna be overwritten. I'd suggest keeping your own version controlled greetings and then I'll integrate them when the frameworks settled.
