### ISSUE TITLE
will.conf example in dev branch

### ISSUE THREAD

**Issue by brenttaylor** [ironman5366/W.I.L.L#36]
I know it's been a while but I've been off working on other projects.  Decided to check back in today and I'm surprised to see a complete rewrite...with most of the same problems as the original had. :)  Lots of dangling file pointers, no adherence to the KISS principle, no data validation, etc.  A lot of this is rather important.

So, trying to get involved again and there is no example of a proper "will.conf" file.  That needs to be there!

**Comment by ironman5366** [comment]
Hi! I definitely need to keep my code clean, I'll work on that! I do have a will.conf, but I don't have an example of it. I'd love to share what I'm working on with you, where do you want to start?

**Comment by Tom-Gorup** [comment]
I can't use will.py without a will.conf. Providing an example is pretty critical to the success of my testing. Any chance you can commit one?

**Comment by ironman5366** [comment]
@Tom-Gorup, I added an example in the latest commit. extended documentation coming soon. Let me know if you have any further questions. https://github.com/ironman5366/W.I.L.L/blob/master/example_will.conf

**Comment by tgorup** [comment]
Thanks!
