### ISSUE TITLE
Simple addition doesn't work

### ISSUE THREAD

**Issue by vihanggodbole** [ironman5366/W.I.L.L#39]
I recently signed up and tried math functions like `2 + 3`. Simple addition does not work. It interprets it as multiplication and gives the answer `6`.

**Comment by ironman5366** [comment]
I don't currently use a custom plugin to handle math, so that data is from wolfram. It seems like it works if you use `2 plus 3`, however I suppose a plugin could be added to handle math specifically. If you want you can make a feature request with this feature and I'll try to get around to it.

**Comment by vihanggodbole** [comment]
Okay. I don't think it's a good idea to have a custom plugin just for maths since wolfram alpha can solve tricky math which you'll  just have to implement it.

**Comment by ironman5366** [comment]
Yeah, my thoughts exactly. If I did one though, I would look into using an API for something like math way, that can solve even more advanced queries

**Comment by vihanggodbole** [comment]
I will try playing around and creating a plugin if possible for this.

**Comment by ironman5366** [comment]
That would be awesome! Let me know what I can do to help.
