### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by brenttaylor** [ironman5366/W.I.L.L#4]
The code base doesn't adhere to a good number of the PEP8 standards and it really should.  It gives everyone, especially code contributors, a style guide they can adhere too.  Especially if they are using a linter (and it looks like you're using IDEA, so you absolutely have a PEP8 linter).

A few examples of issues:
- Tabs over spaces
- Improper spacing between sections of code (two lines separating imports from code, two lines separating functions/classes, etc).

There's actually a lot more, but it's all pretty easily changed. I can work on it before #3 if you'd like.

**Comment by ironman5366** [comment]
Sure, go write ahead. I used idea for part of it, but during development I've probably used 20 different editors and and 4 different os's.

**Comment by narzeja** [comment]
I made a PR (#7). Take a look and see if I covered everything PEP8-wise.

**Comment by ironman5366** [comment]
Amazing, thanks so much
