### ISSUE TITLE
Keys/Tokens should be consolidated into a single config file

### ISSUE THREAD

**Issue by brenttaylor** [ironman5366/W.I.L.L#5]
You have a lot of different API's in use here, most of which need their own Token or API key.  To get this running it's an exercise in running through most of the code base to find where to even enter them.  The slack token for example is in main.py.  Others are in text based config files scattered all over the place.

We should consolidate all of this into a single file.

**Comment by ironman5366** [comment]
Also a good idea that I'm kicking myself for not thinking of. Do you want to take care of it or is this a feature request?

**Comment by brenttaylor** [comment]
I'll be happy to take care of this one too.  This will make other contributions a lot easier since we won't have to keep removing all our API tokens from the code itself every time we commit changes.

EDIT: I'll work on this first and try and get it out tonight.

**Comment by ironman5366** [comment]
Awesome thanks

**Comment by brenttaylor** [comment]
Just an update on this, due to circumstances beyond my control yesterday I didn't get to start on this.  I'll be taking care of it today.

**Comment by ironman5366** [comment]
Awesome, thanks

**Comment by brenttaylor** [comment]
#16 should close this issue

**Comment by ironman5366** [comment]
Thanks
