### ISSUE TITLE
Add pronouns for more than one gender

### ISSUE THREAD

**Issue by sjmog** [ironman5366/W.I.L.L#9]
```
As a gendered user
So W.I.L.L responds with my appropriate pronoun
I would like to tell W.I.L.L my pronoun on initialization
```

**Comment by ironman5366** [comment]
Hi. The only module (I believe) that has gender pronouns would be the personality module (which at the moment isn't hooked up to the main code either). The greetings are gotten from the file personality.txt https://github.com/ironman5366/W.I.L.L/blob/master/personality.txt. The personality.txt file is more of an example, and I wrote the greetings in it for me. If you'd like to add more, different, or modified greetings to yours, it's as easy as typing them. If you want to add a gender configuration to the personality module, I'll add it but as it's a temporary module that's not connected in any way right now I'd rather not spend time editing it. Sorry. 
-Wil

**Comment by sjmog** [comment]
I'm happy to make a PR with some more varied pronouns in the example `personality.txt` - it would feel more inclusive.

**Comment by ironman5366** [comment]
Sure.
